// AthenaCalculator.cxx

// Header for Athena implementation of ASG tool Calculator.
// Template version 5
// This file generated by ./create_tool_wrapper Wed Dec 11 14:52:58 CET 2013.
// Please do not edit.

#include "AthenaCalculator.h"

//**********************************************************************

Calculator::Calculator(const std::string& type,
          const std::string& name,
          const IInterface* parent)
: AthAlgTool(type, name, parent),
  asg::AsgTool(getPropertyMgr()),
  JetSubstructureVariables::Calculator() {
  declareInterface<IProcessTool>(this);
}

//**********************************************************************

Calculator::~Calculator() { }

//**********************************************************************

StatusCode Calculator::initialize() {
  ATH_MSG_INFO("Initializing " << name());
  StatusCode sc = JetSubstructureVariables::Calculator::initialize();
  if ( sc.isFailure() ) {
    ATH_MSG_INFO("Initialization failed");
    return StatusCode::FAILURE;
  }
  ATH_MSG_INFO("Initialization done");
  return StatusCode::SUCCESS;
}

//**********************************************************************

ServiceHandle<StoreGateSvc>& Calculator::evtStore() const {
  return AthAlgTool::evtStore();
}

//**********************************************************************

bool Calculator::msgLvl(MSG::Level lvl) const {
  return AthMessaging::msgLvl(lvl);
}

//**********************************************************************

MsgStream& Calculator::msg() const {
  return AthMessaging::msg();
}

//**********************************************************************

MsgStream& Calculator::msg(MSG::Level lvl) const {
  return AthMessaging::msg(lvl);
}

//**********************************************************************
