// AthenaCalculator.h

// Header for Athena implementation of ASG tool Calculator.
// Template version 4
// This file generated by ./create_tool_wrapper Wed Dec 11 14:52:58 CET 2013.
// Please do not edit.

#ifndef AthenaCalculator_H
#define AthenaCalculator_H

#include "AsgExTool/AsgTool.h"

#include "GaudiKernel/AlgTool.h"
#include "AthenaBaseComps/AthAlgTool.h"
#include "AsgExToolInterface/AthenaIProcessTool.h"

#include "JetSubstructureVariables/Calculator.h"

class Calculator :
  virtual public AthAlgTool,
  virtual public IProcessTool,
          public JetSubstructureVariables::Calculator {

public:

  Calculator(const std::string&, const std::string&, const IInterface*);
    
  ~Calculator();

  StatusCode initialize();

  ServiceHandle<StoreGateSvc>& evtStore() const;

  bool msgLvl(MSG::Level) const;

  MsgStream& msg() const;
  MsgStream& msg(MSG::Level) const;

};

#endif
